### ISSUE TITLE
Preferences per Project

### ISSUE THREAD

**Issue by dinhoabreu** [mikaeljorhult/brackets-php-code-quality-tools#13]
First of all, congratulation for this extension. It's really useful.
But, I would like to know if it has an option to save preferences per project **as** jshint does with **.jshintrc**?

**Comment by phanect** [comment]
+1

I think finding ruleset.xml from the project root is enough.

**Comment by klarkc** [comment]
+1

It could be great

**Comment by cithukyaw** [comment]
It will be great if we have this feature.

**Comment by sascha-tasche** [comment]
+1
