### ISSUE TITLE
Malfunctioning the file selection in the working files.

### ISSUE THREAD

**Issue by cithukyaw** [mikaeljorhult/brackets-php-code-quality-tools#15]
I installed this extension. I notice that it could affect the file selection in the side bar **Working Files** and the title bar.

#### When does the problem occur?

After the extension is installed,

1. File selection highlight in **Working Files** is not working on the first click, but the file content is changed in the right coding area. Just on the second click, the highlight moved to the current open file.
2. The file name on the title bar still remains that of the first opened file.

#### When does the problem not occur?

1. Before the extension is installed
2. After the extension is uninstalled

#### Platform
Windows 7 32-bit
Intel Core i3-3240 3.40GHz
RAM 4GB

#### Screenshot

![brackets-php-code-quality-tools-issue](https://cloud.githubusercontent.com/assets/4285555/5426696/f16c01e8-8394-11e4-891e-3ad9adb011f4.png)

**Comment by mikaeljorhult** [comment]
Is this still an issue in Brackets 1.6?

**Comment by sithu-ab** [comment]
Ah...yes, it does not occur in Brackets 1.5 and 1.6 anymore.

**Comment by cithukyaw** [comment]
It does not occur in Brackets 1.5 and 1.6 anymore. I'm going to close this issue.

**Comment by mikaeljorhult** [comment]
Glad to hear it. Thank you @cithukyaw!
