### ISSUE TITLE
Show errors inline

### ISSUE THREAD

**Issue by hugofonseca** [mikaeljorhult/brackets-php-code-quality-tools#17]
Just like Atom.io with https://github.com/AtomLinter/Linter this extension should report errors and warnings inline.

**Comment by mikaeljorhult** [comment]
This is not supported by Brackets linter right now which this extension uses to trigger events and show the results.

There are a couple of open Trello cards that will implement this functionality but there has not been that much progress yet.

https://trello.com/c/HbygrWHv/1023-epic-linting-code-inspection
https://trello.com/c/z1PBjZxt/588-live-real-time-linting-as-you-type

**Comment by hugofonseca** [comment]
ok, thanks :)
