### ISSUE TITLE
PHP CodeSniffer - Error opening file

### ISSUE THREAD

**Issue by ronaldo-systemar** [mikaeljorhult/brackets-php-code-quality-tools#25]
Everytime I open a file in a local network the follow message shows:

**PHP CodeSniffer - Error opening file; file no longer exists or you do not have access to read the file**

Well, the file is opened, but codesniffer display that error and doesnt work. Any suggestions about fix this? If I run into local machine it works.

**Comment by mikaeljorhult** [comment]
Could you prove some information on your setup? Windows/OS X? Versions of Brackets and the extension? How are you connecting to the volume?

**Comment by ronaldo-systemar** [comment]
Windows 8.1 Pro
Brackets Release 1.6 build 1.6.0-16680 (release 3df0ac6fa)
PHP Code Quality Tools 0.1.9

I'm just opening the file into a mounted volume in network (linux server). The file opens without problem, just the Code Sniffer doesn't work, PHP mess works fine. If I put on local, it works.

**Comment by mikaeljorhult** [comment]
Sounds like there's a problem with paths on the mounted drive. Could you try running the command manually to see if that works?

`php phpcs.phar --standard=PSR2 --report-width=300 {{file}}`
