### ISSUE TITLE
Specify path to php.exe

### ISSUE THREAD

**Issue by FurmanSK** [mikaeljorhult/brackets-php-code-quality-tools#26]
Hi,

Would be awesome if I could some how specify as an option where the php.exe is located. I can't "install" it on my work laptop because of it being locked down but I do have php folder in C:\php. I've tried looking in your source to add it to everywhere I see it calling the command but even then it won't even open preferences if it can't detect php is installed. Otherwise I can't even use this in my development.

**Comment by mikaeljorhult** [comment]
This could probably be done. I'll look into it.

**Comment by FurmanSK** [comment]
Ok, thanks!

**Comment by Amosss** [comment]
+1 I added the php folder to the path and it worked with brackets but when trying to do the same with the portable version, it doesn't recognize php on my computer so it doesn't work. I hope this will be added soon.

**Comment by shakegioh** [comment]
@mikaeljorhult can I make a pull request solving this?

**Comment by shakegioh** [comment]
I added a new text field in settings dialog to save the custom path to php.exe in pull request #36

**Comment by mikaeljorhult** [comment]
Resolved with pull request #36. Will be in next release.
