### ISSUE TITLE
Cannot reopen panel after it has been closed

### ISSUE THREAD

**Issue by hjoelr** [mikaeljorhult/brackets-php-code-quality-tools#28]
First off, thank you for a great extension! It has been so helpful with my coding.

Here's the issue I'm experiencing. For some reason I can't figure out how to re-open the PHP Code Quality Tools panel at the bottom of brackets after I clicked the "X" to close it. If I go to View > PHP Code Quality Tools, it opens the settings to the plugin but clicking "Ok" on the settings window doesn't open the panel. I was looking for a quick button down the right-hand side of brackets where some other extensions have placed themselves, but I don't see any for this extension. Even uninstalling the extension and reinstalling it hasn't opened the panel. Any pointers would be great. Thanks!

P.S. I'll submit [another issue](https://github.com/mikaeljorhult/brackets-php-code-quality-tools/issues/29) for why I closed the panel in the first place.

**Comment by mikaeljorhult** [comment]
The extension uses the Brackets linting API so there should be an icon in the bottom right corner of the window. A check mark indicates no errors while an exclamation mark indicates linting errors in the file. If there are errors you can click it to show the panel.

![lint-icon](https://cloud.githubusercontent.com/assets/215694/13420920/a1d4d882-df8a-11e5-853d-27be77057c81.png)

**Comment by hjoelr** [comment]
@mikaeljorhult Ohhh. Thanks for pointing me in the right direction! That worked to open the panel.
