### ISSUE TITLE
Extension doesn't find PHP

### ISSUE THREAD

**Issue by AndreasSchantl** [mikaeljorhult/brackets-php-code-quality-tools#31]
I have PHP installed according to the php.net manual. But the extension can't find it. Where do I need to install it? 

**Improvement**
Write a install guide in the README.md

**Comment by jocastaneda** [comment]
That will depend on what system you are running. Generally OSX will already detect it, Windows you will have to set the environment variable. I'm not too familiar with Linux OSs so you may have to consult the docs for that.

You can always check if it is set by running `php -v` in any terminal, command line of your choice.

**Comment by AndreasSchantl** [comment]
Thanks for the help. I had to set the system variable in Windows. 

I am really not used to have PHP installed on Windows...

**Comment by jocastaneda** [comment]
Of course! Happy to help. Took me a few nights to figure that one out. Realized I was using the wrong folder name. ( was set to `phpp` not `php` )

**Comment by AndreasSchantl** [comment]
Those small mistakes whicht take you hours afterwards....


Especially true for code when there is no proper compiler for the language ;-)

**Comment by mikaeljorhult** [comment]
Thank you @jocastaneda! So nice to see users helping each other out.

@AndreasSchantl: If you're able to write down the steps you took to make it work I would gladly link to it or host it in a project wiki.

**Comment by AndreasSchantl** [comment]
No problem, @mikaeljorhult! Here is how I did it.

**On Windows**

1. Download PHP from the PHP download section which can be found here:
[http://windows.php.net/download](http://windows.php.net/download)

2. Extract the ZIP in `C:\php`

3. Add a  system environment variable by opening `Control Panel -> System -> Advanced System Settings => (BUTTON)Environment Variables`

4. There, you will find a list with already existing environment variables. Find the variable `Path` and click edit

5. Click new and enter `C:\php`

6. Done - If necessary log off and on again and enjoy Brackets detecting PHP for the PHP Quality Tools

 


**On Linux:**

1. Install PHP according to PHP.net like this:
`# apt-get install php5-common libapache2-mod-php5 php5-cli`

2. Done - the extension will detect it automatically.

**Comment by q2apro** [comment]
This tutorial should definitely be linked from the README file in the root.
