### ISSUE TITLE
PHP Mess Detector output

### ISSUE THREAD

**Issue by hotsleeper** [mikaeljorhult/brackets-php-code-quality-tools#33]
The output from PHP Mess Detector is currently useless.  It shows "Stack trace:" in the Problem description field and the text of the source line in the second field.  It looks like the xml output from PHPMD may have changed or the parser is not pulling the correct fields out. 
![phpmd](https://cloud.githubusercontent.com/assets/18607330/14730943/fca6f1d2-088e-11e6-871a-4de115e8e381.png)

**Comment by mikaeljorhult** [comment]
Looks like Mess Detector is encountering some kind of runtime error. What version of Windows are you seeing this on?

**Comment by hotsleeper** [comment]
Windows 8.1 64bit.

**Comment by mikaeljorhult** [comment]
Awesome! Good to know and great you manage to sort it out.
