### ISSUE TITLE
PHP Mess Detector error

### ISSUE THREAD

**Issue by sekT0id** [mikaeljorhult/brackets-php-code-quality-tools#34]
**PHP Code Quality Tools:** 0.1.11
**System:** ubuntu 16.04 LTS
**Brackets:**  1.6.0-16680
**php -v:** PHP 7.0.4-7ubuntu2 (cli) ( NTS )

Trying to open any php file.
in report panel:

**1 error PHP Mess Detector**

8	Stack trace:	'code from line 8' **(always line 8)**

**Comment by mikaeljorhult** [comment]
You might have to enable bzip2 in your php.ini file (see #33). Could you check to see if it is enabled?

**Comment by sekT0id** [comment]
Thank you!

missed two modules:
**php7.0-bz2**
**php7.0-xml**

**Comment by mikaeljorhult** [comment]
Glad you manage to fix it!
