### ISSUE TITLE
How to Change Code Sniffer Settings

### ISSUE THREAD

**Issue by Mitchell64** [mikaeljorhult/brackets-php-code-quality-tools#40]
Hi,
First, thanks so much for your great extension. 

I'm trying to change some settings for the PHP Code Sniffer and have been unable to find where the appropriate files are. Specifically, I'd like to change the maximum line length. Any help in finding the files to change would be greatly appreciated.

Thanks,
Mitchell

**Comment by mikaeljorhult** [comment]
The extension only supports rulesets currently so you are unfortunately not able to edit individual rules.

**Comment by Nihilivin** [comment]
Yeah, I'd like to change those settings too. I've found a way to create custom rulesets (like [this example](https://gist.github.com/gsherwood/9d22f634c57f990a7c64) for using tabs instead of space for indentation), and I've managed to create a full ruleset that works well with phpcs, but the Bracket's plugin don't seem to find it...

**Comment by GerkinDev** [comment]
Oh, by the way, I've found that ;)
![screenshot from 2017-05-03 14-04-18](https://cloud.githubusercontent.com/assets/8212504/25659740/71a3d156-3009-11e7-816c-8832b616373a.png)
You can install standards, create your rulesets and put them in the `PHP/CodeSniffer/Standards/`directory and the brackets plugin will be able to enable them

Edit: After check, I realized that available standards are hard-coded in the settings form

**Comment by Mitchell64** [comment]
@Nihilivin: Could you provide a little more detail on how you created and added your own ruleset? Maybe an example?

**Comment by AgamlaRage** [comment]
I really need this feature.
Can I help you ? I don't know where to start yet

All of the rules seems to be manage by the [phpmd.phar](https://github.com/mikaeljorhult/brackets-php-code-quality-tools/blob/master/modules/vendor/phpmd/phpmd.phar)

**Comment by GerkinDev** [comment]
My bad, the plugin can't add custom rulesets: they are hard-coded in the settings form and shipped with the plugin. Anyway, it's not that big to add this feature.

@mikaeljorhult are you interested in a PR? Would you be able to test it then release it on the Brackets repo?

**Comment by mikaeljorhult** [comment]
Of course! It's on my road map to support but don't have the time to do it at the moment so all PRs are welcome.
