### ISSUE TITLE
Spaces must be used to indent lines; tabs are not allowed

### ISSUE THREAD

**Issue by abrahammurciano** [mikaeljorhult/brackets-php-code-quality-tools#41]
I always get this error when using tabs. 

`Spaces must be used to indent lines; tabs are not allowed`

But I'm one of those guys who prefers tabs over spaces... what's wrong with using tabs?

Please fix this, or at least someone please help me find a workaround.

**Comment by mikaeljorhult** [comment]
One of the rulesets (PSR-2 maybe?) you use require you to use spaces to be compliant. If you wish to use spaces, just unselect PSR-2 ruleset in the settings.

**Comment by abrahammurciano** [comment]
But wouldn't​ that remove all the rules of PSR-2?
Also, I have looked around but I cannot find where the settings page for this extension is?

**Comment by mikaeljorhult** [comment]
Yes, this would remove all of the PSR-2 rules. The extension uses rulesets and there is currently no way to remove certain rules within a set.

Settings are found through the Edit menu.
