### ISSUE TITLE
Update WordPress standards / specify alternate location?

### ISSUE THREAD

**Issue by ajaydsouza** [mikaeljorhult/brackets-php-code-quality-tools#42]
I'm trying to update the WordPress standards to the latest version by replacing the `rulesets/WordPress` folder with the latest version from the WPCS Github repository.
When I do this, the checks stop working. I can see it in the Preferences pane but the checks don't run.
Replacing the folder with the original from this repo works again.

Is there something I am missing in order to update to the latest WordPress coding standards?

**Comment by mikaeljorhult** [comment]
The new coding standards for WordPress requires a newer version of CodeSniffer than the one that is included in the extension. I'm currently working on updating the extension including new version of tools and rulesets.

If you want to start using it now (and don't mind the occasional broken feature) you could try the master branch which include new version of all the tools.

**Comment by ajaydsouza** [comment]
Happy to test out the versions and can report if anything breaks. Is it as simple as grabbing the master and replacing the folder the contents of the extension folder ( mikaeljorhult.brackets-php-code-quality-tools )

**Comment by mikaeljorhult** [comment]
Yes, you only need to clone the master branch and replace the content in the extension folder.

**Comment by ajaydsouza** [comment]
This works well. Was able to replace the current WordPress standards with the latest that was released last week and they work fine.

**Comment by mikaeljorhult** [comment]
Great! Would you mind making a pull request with the current standards?

**Comment by ajaydsouza** [comment]
Sure. Will do so shortly

**Comment by mikaeljorhult** [comment]
The new ruleset for WordPress are now merged.
